version: '3.8'
services:
  mysql:
    image: mysql:5.7
    networks:
      - ecommerce-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: logistic
      MYSQL_USER: root
      MYSQL_PASSWORD: root
networks:
  ecommerce-mysql: