version: '3.8'
services:
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile.springboot
    ports:
      - "8080:8080"
    networks:
      - ecommerce-mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/logistic
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
networks:
  ecommerce-mysql: